# -*- coding: utf-8 -*-
"""CSE 505 Assignment 2 Problem 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FXoz1ChwJ35l7qDlJ6dnFrLUABLyJP3d

## Part 1
"""

from collections.abc import Iterable

def flatten(l):
    for el in l:
        if isinstance(el, Iterable) and not isinstance(el, (str, bytes)):
            yield from flatten(el)
        else:
            yield el

inlist = [[[2],4],[[[[[6],8]]]],[[9],[[10]]]]
for x in flatten(inlist):
  if x%2 != 0:
    break
  print(x)

"""## Part 2

"""

def flatten2(l, thnk):
    for el in l:
        if isinstance(el, Iterable) and not isinstance(el, (str, bytes)):
            flatten2(el, thnk)
        else:
            thunk(el)

def thunk(x):
  if x%2 != 0:
    raise Exception
  print(x)

inlist = [[[2],4],[[[[[6],8]]]],[[9],[[10]]]]
try:
  flatten2(inlist, thunk)
except Exception:
  pass